### ISSUE TITLE
Clarify package-statement error

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/judge-java12#26]
A student remarked that he did not know what was meant by the "default" package. Students might think that the error is caused because of a missing `package default;` line, or something like that.

I propose to change this to something that encourages the student to actually remove the package statement. Maybe we can also change this to an error-callout to make it more prevalent.

![image](https://user-images.githubusercontent.com/6131398/66951647-2aaa3a00-f05b-11e9-81b5-cb9f4b0ded6f.png)

@bmesuere any comments on this?

**Comment by ninewise** [comment]
If students are told to use packages, they should also be told about the default package, IMHO. We could append something like "Je klasse komt in het default package als je bestand niet begint met een package-statement," but the term should be mentioned.
